[project]
name    = "veryl_sample"
version = "0.1.0"
license = "MIT"

[build]
clock_type    = "posedge"
reset_type    = "async_low"
filelist_type = "absolute"
target        = {type = "source"}

[format]
indent_width = 4

[dependencies]
veryl_sample5 = {git = "https://github.com/dalance/veryl_sample", rev = "c06199e"}
