[project]
name    = "veryl_sample"
version = "0.2.0"
license = "MIT"

[build]
clock_type    = "posedge"
reset_type    = "async_low"
filelist_type = "absolute"
target        = {type = "source"}

[format]
indent_width = 4

[publish]
auto_commit_after_bump    = true
auto_commit_after_publish = true

[dependencies]
